### ISSUE TITLE
question/request

### ISSUE THREAD

**Issue by pavelxdd** [rossy/borderless-window#1]
Hello! Can you consider implementing some of these hacks in mpv?

If the aero snapping was working for borderless window in mpv, that would be very cool.

**Comment by rossy** [comment]
Yeah, I think I'd like some of this code to be in mpv as well, though there is some refactoring I want to do to w32_common.c first.

**Comment by pavelxdd** [comment]
I see, thanks. If you don't mind could you point out the key parts of the code to get the aero snapping working? I'd like to play around with it myself.

**Comment by rossy** [comment]
You should just need WS_SIZEBOX | WS_MAXIMIZEBOX in the window styles for snapping, though adding WS_SIZEBOX will give the window a sizing border that must be removed by handling WM_NCCALCSIZE. Also, as you can see from handle_nccalcsize(), there is another caveat where if you don't forward the first WM_NCCALCSIZE to DefWindowProc, tile/cascade windows won't work.

**Comment by pavelxdd** [comment]
Everything is clear now, thanks.
