### ISSUE TITLE
Passing window data to the window procedure callback.

### ISSUE THREAD

**Issue by pedrior** [rossy/borderless-window#2]
I'm trying to implement the core code in a custom WPF Window, but i've problems with the data communication.

In your code you pass the * Window structure via CreateWindowExW (lParam) - OK.
How do I do this, taking into account that I do not have access and can not make the call of this function?

If you can help me, I'll be very grateful. Thanks in advance.

**Comment by rossy** [comment]
Passing a structure in lpParam to CreateWindowExW and storing it in GWLP_USERDATA is a C/C++ convention for associating private data with a window in the non-object-oriented Windows API. In WPF, you shouldn't have to worry about it. Just make all the members of `struct window` members of your `Window` subclass, and you should be able to access them directly in your WndProc hook. This means you won't have to worry about saving/loading the pointer to the window data (with SetWindowLongPtrW/GetWindowLongPtrW) either.

As for the code in main() after CreateWindowExW (eg. the call to handle_compositionchanged(),) that should probably go in your Window.OnSourceInitialized method (I think.)
